# Generated by Django 5.2.4 on 2025-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(default='waregamoses20@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
